"""
constants/paragraph4_tokens.py

PRD v1.6 critical-path de-risk (FR-02.5): Paragraph 4 of the AI narrative
is NEVER generated by the LLM. The pipeline writes one of three sentinel
tokens to the `paragraph_4` field, and this module resolves that token to
final text at render time (06:50 IST) with ZERO LLM calls and zero network
latency in the critical window.

Do not generate these strings dynamically. They are fixed, reviewed,
compliance-safe text blocks, exactly as specified in the PRD.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Token constants (sentinel strings written to the pipeline run payload)
# ---------------------------------------------------------------------------

FLAT_OVERRIDE_TOKEN = "__FLAT_OVERRIDE__"
DIVERGENCE_TOKEN_PREFIX = "__DIVERGENCE__"
# Standard (no-divergence, no-flat) scenario uses a blank string sentinel —
# the LLM output for paragraph_4 is "" by contract (FR-02.5).
STANDARD_TOKEN = ""


# ---------------------------------------------------------------------------
# Branch A — FLAT BIAS SHORT-CIRCUIT resolution (fixed, hardcoded string)
# ---------------------------------------------------------------------------

FLAT_OVERRIDE_RESOLUTION = (
    "GIFT Nifty is currently trading flat (meaning its price change is "
    "virtually unchanged from yesterday's close). This tells us that early "
    "morning trading is quiet, and the market is highly likely to open flat "
    "with no clear direction at 09:15 AM IST. Watch the opening half-hour "
    "closely to see if a clear trend emerges."
)

FLAT_OVERRIDE_CALLOUT_TEMPLATE = (
    "GIFT Nifty: {value} | Change: {pct_change}% | Signal: \u27A1\uFE0F Flat Opening Expected"
)


# ---------------------------------------------------------------------------
# Branch B — Structural Divergence resolution template
# ---------------------------------------------------------------------------

DIVERGENCE_RESOLUTION_TEMPLATE = (
    "GIFT Nifty is pointing {direction} this morning, but the overnight "
    "{event} sends a {signal} signal. Watch the first 15 minutes of trading "
    "carefully \u2014 the opening move may reverse once the domestic session "
    "establishes direction."
)


# ---------------------------------------------------------------------------
# Standard (no divergence, no flat) resolution template
# ---------------------------------------------------------------------------

STANDARD_RESOLUTION_TEMPLATE = (
    "Based on overnight signals, the market is expected to {bias_label}. "
    "The primary driver is {top_signal_plain_english}."
)


# ---------------------------------------------------------------------------
# GIFT Nifty Callout Box — non-divergence scenarios (FR-02.5)
# ---------------------------------------------------------------------------

GIFT_NIFTY_CALLOUT_STANDARD_TEMPLATE = (
    "GIFT Nifty is currently trading at {value}, which is {pct_change}% "
    "{direction_word} than yesterday's Nifty 50 close of {prev_close}. "
    "GIFT Nifty (think of it as an early morning preview of how Indian "
    "markets will open, traded at GIFT City, India from 06:30 AM each day) "
    "suggests the market may open {direction_word} today."
)


def build_divergence_token(direction: str, event: str, signal: str) -> str:
    """
    Build the structured interpolation token exactly as specified in FR-02.5:

        __DIVERGENCE__|DIRECTION:[higher/lower]|EVENT:[...]|SIGNAL:[conflicting/opposing]

    The bracketed fields are populated by the pipeline from structured data,
    never by the LLM.
    """
    return f"{DIVERGENCE_TOKEN_PREFIX}|DIRECTION:[{direction}]|EVENT:[{event}]|SIGNAL:[{signal}]"


def parse_divergence_token(token: str) -> dict:
    """Parse a __DIVERGENCE__ token back into its three variable fields."""
    if not token.startswith(DIVERGENCE_TOKEN_PREFIX):
        raise ValueError("Not a divergence token")
    parts = token.split("|")[1:]  # drop the __DIVERGENCE__ prefix segment
    fields = {}
    for part in parts:
        key, _, value = part.partition(":")
        fields[key.strip().lower()] = value.strip("[]")
    return fields


def resolve_paragraph_4(
    token: str,
    *,
    bias_label_plain: str = "",
    top_signal_plain_english: str = "",
) -> str:
    """
    Resolve any Paragraph 4 sentinel token to final rendered text.
    This function makes ZERO network or LLM calls — pure string templating.
    """
    if token == FLAT_OVERRIDE_TOKEN:
        return FLAT_OVERRIDE_RESOLUTION

    if token.startswith(DIVERGENCE_TOKEN_PREFIX):
        fields = parse_divergence_token(token)
        return DIVERGENCE_RESOLUTION_TEMPLATE.format(
            direction=fields.get("direction", "higher"),
            event=fields.get("event", "a global macro event"),
            signal=fields.get("signal", "conflicting"),
        )

    # Standard / blank scenario
    return STANDARD_RESOLUTION_TEMPLATE.format(
        bias_label=bias_label_plain or "open broadly in line with overnight signals",
        top_signal_plain_english=top_signal_plain_english or "overnight global market direction",
    )
